# YAML file for a Streamlit dashboard environment
#
# Install this environment using:
#   conda env create -f path/to/environment.yml
# Activate the environment using:
#   conda activate slf-sdc-rainfall-app

name: slf-sdc-rainfall-app
channels:
  - conda-forge

dependencies:
  # --- Python Version ---
  - python=3.12         # Specify the Python version

  # --- Core Data Library ---
  - numpy               # For numerical operations
  - pandas              # For data manipulation and analysis
  - netcdf4             # For reading NetCDF (.nc) files

  # --- Plotting & Visualization ---
  - altair              # For declarative statistical visualization
  - matplotlib          # For creating static, animated, and interactive visualizations

  # --- Web App ---
  - streamlit           # For creating the interactive web application

  # --- Domain-Specific Libraries ---
  - imdlib              # For downloading IMD gridded data

  # --- Pip ---
  - pip                 # Ensures pip is installed in the environment
  # - pip:
  #   - package-from-pypi # Use this section for packages not on conda-forge